version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Clerk API
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_c3RpcnJpbmctc2FpbGZpc2gtNjcuY2xlcmsuYWNjb3VudHMuZGV2JA
      CLERK_SECRET_KEY: sk_test_zyx0dNyDK9RzgbHk3799HdAWoBfeYgyH8Vbvcv1pad
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
      NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /onboarding
      NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /onboarding

      # Database
      DATABASE_URL: "postgresql://postgres:29_Oct2006@db.fudiqrjbjecvnwymcqmk.supabase.co:5432/postgres?schema=public&sslmode=require"

      # Google API
      GOOGLE_API_KEY: "AIzaSyBf9Ar7-9T0WZ2_5lcE48uCYY6AMdVvNSc"

    depends_on:
      - db
    command: npm start

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 29_Oct2006
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
